---
apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak-service
  namespace: kube-system
  labels:
    app: postgres-keycloak
spec:
  ports:
  - name: postgres-keycloak-port
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres-keycloak
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-keycloak
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-keycloak
    spec:
      containers:
        - name: postgres-keycloak-container
          image: postgres
          imagePullPolicy: IfNotPresent
          env:
            - name: PGDATA
              value: "/db/db-files/"
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: keycloak
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /db
              name: postgresdata
            # - name: postgres-keycloak-config-file
            #   mountPath: /docker-entrypoint-initdb.d/keycloak.sql
            #   subPath: keycloak.sql
      volumes:
      # - name: postgres-keycloak-config-file
      #   configMap:
      #     name: postgres-keycloak-config
      #     items:
      #     - key: keycloak.sql
      #       path: keycloak.sql
      - name: postgresdata
        hostPath:
          path: /data_deployment/postgres-keycloak
          type: DirectoryOrCreate
---