---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: keycloak
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
      - name: postgreschecker
        image: jonasscherer/service_checker:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: WAIT
            value: "postgres,postgres-keycloak-service.kube-system.svc.cluster.local,5432"
          - name: DELAY
            value: "2"
      containers: 
        - name: keycloak-container
          image: jboss/keycloak:4.8.3.Final
          imagePullPolicy: IfNotPresent
          args: ["-b","0.0.0.0","-c", "standalone-ha.xml", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir","-Dkeycloak.migration.dir=/opt/jboss/keycloak/standalone/configuration/import","-Dkeycloak.migration.strategy=IGNORE_EXISTING"]
          env:
          - name: KEYCLOAK_USER
            value: admin
          - name: KEYCLOAK_PASSWORD
            value: admin
          # - name: KEYCLOAK_HOSTNAME
          #   value: 192.168.99.102
          - name: DB_VENDOR
            value: "postgres"
          - name: DB_ADDR
            value: "postgres-keycloak-service.kube-system.svc.cluster.local"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "keycloak"
          - name: DB_PASSWORD
            value: "keycloak"
          - name: DB_PASSWORD
            value: "keycloak"
          - name: KEYCLOAK_HTTP_PORT
            value: "8080"
          - name: KEYCLOAK_HTTPS_PORT
            value: "8443"
          - name: NAME
            value: "postgres"
          - name: NAME
            value: "postgres"
          - name: ROOT_LOGLEVEL
            value: "WARN"
          - name: KEYCLOAK_LOGLEVEL
            value: "WARN"
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          ports:
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8443
          - name: admin
            containerPort: 9990
          volumeMounts:
            - name: keycloak-import
              mountPath: /opt/jboss/keycloak/standalone/configuration/import
            - name: tls-config
              mountPath: "/etc/x509/https"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
      - name: keycloak-import
        configMap:
          name: keycloak-config
      - name: tls-config
        secret:
          secretName: tls-secret
---
